version: '3.8'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./db/storage/docker/clickhouse:/var/lib/clickhouse
      - ./db/logs:/var/log/clickhouse-server
      - ./db/data:/var/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 8224:8123
      - 9224:9000
    restart: unless-stopped
    logging:
      options:
        max-size: "5m"
        max-file: "1"
#  mysql:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=verysecret
#      - MYSQL_DATABASE=yii2advanced
#      - MYSQL_USER=yii2advanced
#      - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret