version: '3.8'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    command: sh -c "composer install --ignore-platform-reqs && php init --env=Production --overwrite=n"
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./db/storage/docker/clickhouse:/var/lib/clickhouse
      - ./db/logs:/var/log/clickhouse-server
      - ./db/data:/var/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 8224:8123
      - 9224:9000
    restart: unless-stopped
    logging:
      options:
        max-size: "5m"
        max-file: "1"